version: '3.8'

services:
  webserver:
    container_name: PHP-webserver
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
    ports:
      - 80:80
  db:
    image: mysql
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: "Asia/Bangkok"
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: projectscg
      MYSQL_USER: myuser
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  db_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/mysql


